### ISSUE TITLE
Counting categories

### ISSUE THREAD

**Issue by morvael** [BattleScribe/Release#3]
Please check the attached test case.

I think that:
`increment "stat 1" by 1, repeat 1 times for every 1 selections of "category"`
should work as well as
`increment "stat 1" by 1, repeat 1 times for every 1 selections of "entry"`
by counting entries that have given category selected.

Unfortunately only the "entry" method works.

Test case
[link](https://drive.google.com/open?id=1xA7Ud9sy14asaywymY3gmh0LJfJMMBVM)

**Comment by Jonskichov** [comment]
Fixed in 2.01.11.104 on desktop

Android and iOS builds coming in the next day or so

**Comment by amis92** [comment]
@Jonskichov is that so? Well, maybe the error is somewhere else, but I still can't get T'au Commander to work.

Repro:

1. Add T'au Empire (v23) Patrol Detachment
2. Add Game Type, select Matched
3. Add 2x Commander in XV8
4. Observe no error (except about required Troops choice)

Expected: Error "You have 1 too many Commanders in Patrol Detachment" (or similar) because of the constraint on `Commander` category.

**Comment by Jonskichov** [comment]
@amis92 Taking a look now - the original issue _is_ fixed, though there is another issue that's causing you problems :)

**Comment by Jonskichov** [comment]
@amis92 Should be sorted in 2.01.12 :)

**Comment by Jonskichov** [comment]
Fixed in 2.01.17.270 on Android

**Comment by Jonskichov** [comment]
Fixed in 2.01.15.113 on iOS
